import { useEffect } from 'react'

const projects = [
  {title:'Surely, AI Can', image:'/images/large/surelyaican.jpg', href:'https://surelyaican.com/', text:'A parody AI benchmarking site that shows the surprising ways frontier models fail.'},
  {title:'Parsem: AI Search Redesigned', image:'/images/large/parsem.png', href:'https://parsemsearch.app/', text:'AI search rebuilt for transparency — every part of each answer links to a real, visible source, giving credit back to the people who wrote it.'},
  {title:'Every Creeping Thing', image:'/images/thumbs/ectsmall.png', href:'/ect.html', text:'A 3D game where the player sees the world from the perspective of different animals. Sound design by Seth S. Scott.'},
  {title:'Standard Assets', image:'/images/thumbs/standardassetssmall.gif', href:'https://alxdncn.itch.io/standard-assets', text:'An experimental 3D game examining the environment package of Unity Standard Assets.'},
  {title:'On Nature', image:'/images/thumbs/OnNatureGif-small.gif', href:'https://alxdncn.itch.io/on-nature', text:'A web game depicting an environment in different representational modes.'},
  {title:'Space Kitty', image:'/images/thumbs/spacekittysmall.png', href:'https://tafkaf.itch.io/space-kitty', text:'A digital and physical game where players use their phone flashlights to protect a space kitty from dogliens. Collaboration with Karina Popp.'},
  {title:'Small Song', image:'/images/thumbs/smallsongsmall.png', href:'https://alxdncn.itch.io/small-song', text:"A short interactive interpretation of A.R. Ammons's twelve-word poem, using the player's location and time to determine the sun and lighting."},
  {title:'Flora', image:'/images/thumbs/florasmall.png', href:'https://gamejolt.com/games/flora/54787', text:'Help a small tree survive the seasons and grow to be a giant of the forest.'},
]

const professional = [
  {title:'Liteforms', image:'/images/thumbs/liteforms-small.gif', href:'https://lookingglassfactory.com/liteforms', text:"A desktop application for talking to and creating holographic characters. A design exploration of embodied AI for Looking Glass displays, where I’m the product lead."},
  {title:'Holographic Elemental', image:'/images/large/elemental-pixar-large.gif', href:'https://blog.lookingglassfactory.com/thattimewewenttopixar/', text:"For Pixar’s Elemental, I supported the team with visual design for bringing Ember and Wade to a Looking Glass display."},
  {title:'Bulgari Holographic Experience', image:'/images/thumbs/OctoFinissimo-small.png', href:'https://www.linkedin.com/posts/ennio-piccirillo_digital-storytelling-experience-activity-7028844964054806528-0Dqy/', text:"A pop-up holographic experience in Rome showcasing the Octo Finissimo Ultra. I worked on the interaction and visual design."},
  {title:'Investing in Futures', image:'/images/thumbs/InvestingInFutures-small.png', href:'https://moreandmore.world/', text:'A card game prompting players to imagine alternative global futures. I contributed to the game design for More&More Unlimited.'},
  {title:'Holo Weather', image:'/images/thumbs/WeatherAppSmall.png', href:'https://lookingglassfactory.com/', text:'A HoloPlayer One app for exploring weather around the world through voice commands and Amazon Echo. Art by Jeff Chang.'},
  {title:'DESIGNxBOULDER', image:'/images/thumbs/designxbouldersmall.png', href:'https://www.bmoca.org/2016-2017-exhibitions/designxboulder', text:'An interactive visualization of projects by Natalie Jeremijenko, displayed at the Boulder Museum of Contemporary Art in 2016.'},
]

const writing = [
  {title:'Finding Wriggle Room: How I Made a Maggot Simulator', href:'https://issuu.com/independenceamazing/docs/a_maze_magazin_nr_4_druck_01/16', text:'Critical and creative considerations behind my thesis, Every Creeping Thing. Published by A MAZE Magazine.'},
  {title:'Savage Beasts: Civilization and Wilderness in Skyrim', href:'https://www.firstpersonscholar.com/', text:'A look at the divisions between human civilization and hostile wilderness in Skyrim. Published by First Person Scholar.'},
  {title:'When Lions Speak', href:'/whenlionsspeak.html', text:'An analysis of how non-human animal avatars in games reflect and reinforce problematic power structures.'},
  {title:'Time is Money', href:'/timeismoney.html', text:"Cart Life, time management, and the instrumentalization of time in games and everyday life."},
  {title:'Ladies’ Man: Womanizing in The Witcher', href:'https://ontologicalgeek.com/ladies-man-womanizing-in-the-witcher/', text:'A critical look at the mechanics of seduction and sex in The Witcher.'},
  {title:'The Animist Blog', href:'https://theanimistblog.wordpress.com/', text:'An archive of my older essays.'},
]

function Header(){ return <header className="site-header"><a className="wordmark" href="/"><span>Alex</span> Duncan</a><nav><a href="/portfolio.html">Work</a><a href="/#writing">Writing</a><a href="/about.html">About</a></nav></header> }
function Arrow(){ return <span aria-hidden="true">↗</span> }
function ProjectGrid({items}){ return <div className="project-grid">{items.map((p,i)=><article className="project" key={p.title} style={{'--delay':`${i*45}ms`}}><a className="project-image" href={p.href}><img src={p.image} alt={`${p.title} project preview`}/><span className="project-index">{String(i+1).padStart(2,'0')}</span></a><div className="project-copy"><h3><a href={p.href}>{p.title} <Arrow/></a></h3><p>{p.text}</p></div></article>)}</div> }
function SectionHead({kicker,title,action}){ return <div className="section-head"><div><p className="kicker">{kicker}</p><h2>{title}</h2></div>{action&&<a className="text-link" href={action.href}>{action.label} →</a>}</div> }
function Layout({children}){ return <><Header/><main>{children}</main><footer><p>Alex Duncan</p><p>Brooklyn, New York · <a href="mailto:alxdncn@gmail.com">alxdncn@gmail.com</a></p><p>Games, technology & interactive art</p></footer></> }

function Home(){ return <Layout><section className="hero"><div><p className="kicker">Product manager · Technologist · Artist</p><h1>Ideas for unfamiliar <em>worlds.</em></h1></div><p className="hero-note">I make games, interactive art, AI experiences, and holographic software—often exploring how technology changes our relationship with the natural world.</p><div className="orb" aria-hidden="true"><span/></div></section><section><SectionHead kicker="01 / Selected work" title="Games & interactive art" action={{href:'/portfolio.html',label:'View all work'}}/><ProjectGrid items={projects.slice(0,4)}/></section><section id="writing"><SectionHead kicker="02 / Selected writing" title="Critical practice"/><div className="writing-list">{writing.map((w,i)=><a href={w.href} className="writing-row" key={w.title}><span>{String(i+1).padStart(2,'0')}</span><h3>{w.title}</h3><p>{w.text}</p><Arrow/></a>)}</div></section><section className="contact"><p className="kicker">03 / Contact</p><h2>Questions, collaborations,<br/>or just want to say hi?</h2><a className="button" href="mailto:alxdncn@gmail.com">Get in touch <Arrow/></a></section></Layout> }
function Portfolio(){ return <Layout><div className="page-intro"><p className="kicker">Selected work · 2015—2026</p><h1>Projects</h1><p>Games, interactive art, AI experiments, and holographic experiences.</p></div><section><SectionHead kicker="01" title="Game / art projects"/><ProjectGrid items={projects}/></section><section><SectionHead kicker="02" title="Professional work"/><ProjectGrid items={professional}/></section></Layout> }
function About(){ return <Layout><div className="page-intro about-intro"><p className="kicker">About</p><h1>Alex Duncan</h1><p className="lede">I’m a product manager and technologist living in Brooklyn.</p></div><section className="prose about-grid"><div><p>I manage the software that powers the holographic displays made at <a href="https://lookingglassfactory.com">Looking Glass</a>. I grew up in Vancouver, Canada, did my MFA at the NYU Game Center, and enjoy writing and making weird digital experiences.</p><p>I like to hike, kayak, bird watch, play chess, and read speculative fiction.</p></div><div><p>My creative and critical work often centers on the way humans relate to non-human animals and the natural environment, the way natural spaces are depicted in digital media, and how novel technologies impact social structures.</p><p><a href="mailto:alxdncn@gmail.com">Email</a> · <a href="https://www.linkedin.com/in/alex-duncan-a3082a123/">LinkedIn</a></p></div></section></Layout> }

const essays = {
  '/savagebeasts.html': {title:'Savage Beasts: The Spatial Conflict Between Civilization and Wilderness in The Elder Scrolls V: Skyrim', paragraphs:[`In The Elder Scrolls V: Skyrim, players encounter a vast virtual environment, populated by numerous and diverse creatures. The virtual space of the game, however, is not homogeneous. Various aspects of its representation and structure create a division between urban space, or civilization, and the non-urban natural environment, or wilderness. The differences between these two spaces create a world in which the natural environment is seen as threateningly hostile, a space that must be overcome and dominated.`, `As ecofeminist thinkers like Val Plumwood have stressed, the binary division between civilization and nature is part of the conceptual structure justifying race- and gender-based oppression: those aligned with nature and wilderness are different and inferior, and so can be denied full rights and colonized. The environment depicted in Skyrim is a virtual one, but the paradigm it reflects and reinforces has dire consequences for all things deemed “natural.”`, `This essay is currently under consideration for publication.`]},
  '/timeismoney.html': {title:'Time is Money: Cart Life and the Instrumentalization of Time', paragraphs:[`In his book 24/7: Late Capitalism and the Ends of Sleep, Jonathan Crary writes that “sleep is an uncompromising interruption of the theft of time from us by capitalism.” In contemporary capitalist societies, individuals’ time is instrumentalized for production, circulation, and consumption, with the one exception of the time when they are asleep. A similar representation can be seen in digital games, where waking time is directed towards completing missions and gaining currency.`, `This paper shows how Richard Hofmeier’s Cart Life uses goal-based mechanics to comment on the instrumentalization of people’s time due to financial concerns. With a clock that moves relentlessly forward, tasks that require precise timing, and an overall deadline, every moment must be optimized. The rare exception is sleeping time, which serves as a welcome rest from the intensity of waking life, though one constantly encroached upon.`, <>This paper was presented at the <a href="https://extendingplay.rutgers.edu/">Extending Play conference</a> at Rutgers University.</>]},
  '/whenlionsspeak.html': {title:'When Lions Speak: Representations of Non-Human Avatars in Digital Games', paragraphs:[`When we play a game where the avatar is a non-human animal, how is this experience of otherness represented, if at all? This paper takes Might and Delight’s Shelter and Maxis’s Spore as case studies to examine the ways digital games typically reinscribe a logocentric framework that posits animal ontology as inferior.`, `This framework has a long history in Western philosophy and finds one of its most coherent articulations in the work of René Descartes. Descartes locates human subjectivity in the possession of a rational mind. In denying this capacity in other life-forms, he also deprives them of subjectivity, individuality, and the rights of individuals.`, `The lack of nuance with which Shelter and Spore treat animal avatars reflects this traditional representation through an emphasis on visual perception, lack of individual differentiation, symbolization of the avatar, and use of traditional control schemes. Drawing on Jacques Derrida, Giorgio Agamben, Cary Wolfe, and Brian Massumi, I suggest alternative approaches to representing non-human animals as game avatars.`, <>A version was presented at the <a href="https://gameslit15.wordpress.com/">Games and Literary Theory conference</a>. An expanded version was presented at <a href="https://digra.org/">DiGRA 2016</a>.</>]}
}
function Essay({essay}){ return <Layout><article className="essay"><p className="kicker">Writing · Abstract</p><h1>{essay.title}</h1><div className="prose">{essay.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</div></article></Layout> }
function Ect(){ return <Layout><article className="essay project-detail"><p className="kicker">Game · MFA thesis</p><h1>Every Creeping Thing</h1><p className="lede">A game about embodying different animal species.</p><a className="button" href="https://alxdncn.itch.io/every-creeping-thing">Play the game <Arrow/></a><img src="/images/ect/ecttitle.png" alt="Every Creeping Thing title screen"/><div className="prose"><p>Challenging you to imagine the world from a perspective far removed from your own, it is a 3D game in three parts, each representing a unique creature’s viewpoint. Strange visual effects and unconventional controls ask the player simply to understand how to exist in a new, alien perspective.</p><img src="/images/thumbs/ect.png" alt="Underwater scene from Every Creeping Thing"/><p>Over the course of the game, the player moves from the perspective of a trout to a mayfly to a larva. It is a short, atmospheric experience that challenges the player to reconsider their relationship to the environment and the creatures they share it with.</p><img src="/images/ect/mayfly.png" alt="Mayfly perspective"/><p>Every Creeping Thing was my thesis project for my MFA at the NYU Game Center. After researching depictions of non-human animals as avatars, I tried to make a game that took a different approach.</p><img src="/images/ect/larva.png" alt="Larva perspective"/><p>Read more about its making in <a href="https://issuu.com/independenceamazing/docs/a_maze_magazin_nr_4_druck_01">A MAZE magazine’s animals issue</a>.</p></div></article></Layout> }

export default function App(){ const path=window.location.pathname.toLowerCase(); useEffect(()=>{window.scrollTo(0,0)},[path]); if(path.endsWith('/portfolio.html')) return <Portfolio/>; if(path.endsWith('/about.html')) return <About/>; if(path.endsWith('/ect.html')) return <Ect/>; const essay=essays[path]; if(essay) return <Essay essay={essay}/>; return <Home/> }
